### PR TITLE
debug: debug command print cpu information, fix #1735

### LINKED ISSUE #1735: [Bug Report]: 维测模块没有打印多核系统上的cpu绑定信息
### 联系方式

_No response_

### 您发现了什么问题

A bug happened!
运行环境:
固件版本:

### 分支

master (Default)

### 请选择您发现此问题的解决方案名称

_No response_

### 日志

_No response_

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
Debug cli command prints cpu_binded/cpu_num/cpu_exec information on
multi-core cpu.

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : c55b6f9af29e4a3d74fe8d30c0c432779ac7547e

**Comment by skylarCai** [comment]
auto build success,number:175

**Comment by skylarCai** [comment]
autotest success,number:1396

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

File: components/debug/src/debug_overview.c [hunk 1]
```diff
@@ -101,7 +101,8 @@ static void debug_task_show(int (*print_func)(const char *fmt, ...), ktask_t *ta
     const name_t *task_name;
 
     char s_task_overview[] = "                              0x         0x      "
-                             "   0x        (0x        )\r\n";
+                             "   0x        (0x        )                        "
```
Comment (skylarCai) [inline components/debug/src/debug_overview.c:104]: LGFM

**Review by skylarCai — COMMENTED** [review]
no security risk
