### PR TITLE
Change the return value type, fixed #1736

### LINKED ISSUE #1736: [Bug Report]:use enum type as boolean
An enum-typed expression is used in a Boolean conditional context. The enum type does not appear to have a distinguished false (zero) value

### PR DESCRIPTION
**Pull request by YiluMao**
An enum-typed expression is used in a Boolean conditional context. The
enum type does not appear to have a distinguished false (zero) value.

Change the type as int to fix such issue.

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : e1d67c42972d307afe38fb4e1a64d01b897cfb74

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Comment by skylarCai** [comment]
auto build success,number:174

**Comment by skylarCai** [comment]
autotest success,number:1395

File: hardware/chip/haas1000/aos/ota_port.c [hunk 1]
```diff
@@ -243,7 +243,7 @@ void ota_set_zoneAB_bootinfo_to_default(void)
 
 enum bootinfo_zone ota_get_valid_bootinfo_zone(void)
 {
-    enum bootinfo_zone ret = OTA_BOOTINFO_ZONEA;
+    int ret = OTA_BOOTINFO_ZONEA;
```
Comment (skylarCai) [inline hardware/chip/haas1000/aos/ota_port.c:246]: LGFM

**Review by skylarCai — COMMENTED** [review]
no security risk
